<!DOCTYPE html>
<html>
	<head>
		<title>Story Time With Lucia</title>
		<link media="screen" type="text/css" href="style/template.css" rel="stylesheet">
		<link media="screen" type="text/css" href="style/not-post-style.css" rel="stylesheet">
		<link media="screen" type="text/css" href="style/normalize.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<?php
				include 'page-element/navbar.html';
			?><div class="titlewrap">
				<?php
					$title_page == false;

					include 'page-element/post-display-sql.html';
				?>
				<audio src="audio/The-Valley-William-and-Sly-Lucas-Paakh.mp3" controls autoplay loop>
			</div>
		</div>
	</body>

</html>