<!DOCTYPE html>

<html> 
	<head>
		<title>Story Time With Lucia</title>
		<link media="screen" type="text/css" href="style/template.css" rel="stylesheet">
		<link media="screen" type="text/css" href="style/not-post-style.css" rel="stylesheet">
		<link media="screen" type="text/css" href="style/normalize.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<div class="titlewrap">
				<div class="title">
					<h1>Story Time With Lucia</h1>
					<h5>...Throughout which Lucia continues to delve into further layers of abstraction until the universe becomes devoid of all meaning</h5>
				</div>
				<div class="about-wrap">
					<div class="me">
						<div class="about">
							<img class="meimg" src="img/lucia.png">This is my description of me... On second thoughts, let's not go there. It is a silly place. We want a shrubbery!! Well, how'd you become king, then? Now, look here, my good man.
						</div>
					</div>
					<div class="page">
						<div class="about" id="float-text-right">
							<img class="pageimg" src="img/imagination.jpg">This is my description of my blog-cum-storytelling-base... Bloody Peasant! But you are dressed as one… Ah, now we see the violence inherent in the system! The nose?
						</div>
					</div>
				</div>
			</div>
			<!--include navbar-->
			<?php
				include 'page-element/navbar.html';
			?>
			<div class="postwrap">
				<?php
					$title_page == true;
					include 'page-element/post-display-sql.html';
				?>
				<div class="sideimg">
					<img src="img/cyberman.png">
				</div>
			</div>
			<audio src="audio/The-Valley-William-and-Sly-Lucas-Paakh.mp3" controls autoplay loop>
		</div>
	</body>
<html>